= Upper Entity Model

== Overview

The most general characteristics of Entities are considered to consist of just:

* the definitional properties of each Entity type;
* the relationships between them.

The top-level universal Entity is represented by the generic class `Entity`. Descendants of this class will add properties pertinent to the type it represents.

Indicative conceptual relationships are shown in this model using direct UML associations with names of the form `'r_xxx'`, as explained above. These could be used within software and databases if desired, however, concrete representation is more likely to be achieved by instantiating the relationship classes `Entity_relationship` and `Relationship_group` described here.

The following UML diagram illustrates the upper Entity model.

[.text-center]
.rm.entity
image::{uml_diagrams_uri}/ENTITY-entity.svg[id=entity_entity, align="center"]

== Taxonomy

The concrete representation chosen for connecting relationships to owning Entities is intended to facilitate realistic database implementations containing very large numbers (e.g. O(100m)) of Entities, potentially with large numbers of relationships (e.g. O(100)).

`Entity` instances are accordingly stored only with their related `Relationship_group` objects, which contain the _identifiers_ of target `Entity_relationship` objects. This approach allows flexible lazy loading of potentially large structures. It is assumed that the `_uid_` field inherited from `Locatable` is used as the identifier for both Entity and Entity Relationship instances.

== Archetyping

TBD

== Class Definitions

include::{uml_export_dir}/classes/{pkg}entity.adoc[]

include::{uml_export_dir}/classes/{pkg}entity_relationship.adoc[]

include::{uml_export_dir}/classes/{pkg}entity_relationship_group.adoc[]
