= Preface

== Purpose

This document describes the architecture of the {product_name} Entity Information Model. The semantics are drawn from the {openehr_rm_demographic}[openEHR Demographic Information Model^] and ontologies, including the {bfo}[Basic Formal Ontology (BFO)^].

The intended audience includes developers of health informatics standards; implementers and health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^].

Related documents include:

* The {s2_base_patterns}[S2 Patterns Model^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_entity_latest_entity}[{s2_entity_latest_entity}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Prior Art

The 'social entity' part of this specification has origins in the work that led to the {openehr_rm_demographic}[openEHR Demographic Model^]. The 'physical entity' part is based on {bfo}[Basic Formal Ontology^].

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an {product_name} specification is determined by a formal test of that artifact against the relevant {product_name} Implementation Technology Specification(s) (ITSs), such as a JSON-schema or OpenAPI specification. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.


