= Revision History

.[click here]
[%collapsible]
====

[cols="1,6,2,2", options="header"]
|===
|Issue|Details|Raiser|Completed

4+^h|*BASE Release 0.8.7*

|[[latest_issue]]0.8.7
|{spec_tickets}/S2ENTITY-10[S2ENTITY-10^]: Replace `domain_type` attribute with inheritance from `Info_item`.
 {spec_tickets}/S2ENTITY-11[S2ENTITY-11^]: Replace domain specific `Info_item` descendant types with `Info_item`.
 {spec_tickets}/S2ENTITY-12[S2ENTITY-12^]: Convert `Accountability` class to `Node`.
|T Beale
|[[latest_issue_date]]04 Nov 2024

4+^h|*BASE Release 0.8.6*

|0.8.6
|{spec_tickets}/S2ENTITY-9[S2ENTITY-9^]: Move `Party` subordinate classes to BASE as subtypes of `Info_node`.
|T Beale
|07 Oct 2024

4+^h|*BASE Release 0.8.5*

|0.8.5
|{spec_tickets}/S2ENTITY-3[S2ENTITY-3^]: Improve Party details, including addresses, identity; +
 {spec_tickets}/S2ENTITY-6[S2ENTITY-6^]: Create Entity_kind hierarchy, and convert Physical entity hierarchy to xxx_kind; +
 {spec_tickets}/S2ENTITY-7[S2ENTITY-7^]: Add new physical entity hierarchy to represent individuals; +
 {spec_tickets}/S2ENTITY-8[S2ENTITY-8^]: Add support for occurrents, including processes
|T Beale
|15 Oct 2022

|0.3.0
|{spec_tickets}/SPECRM-?[SPECRM-?^]: Initial writing; adapted from Demographic IM.
|T Beale
|15 Oct 2022

|===

====