= Preface

== Purpose

This document describes the architecture of the S2 Entity Information Model. The semantics are drawn from the {openehr_rm_demographic}[openEHR Demographic Information Model^] and ontologies, including the {bfo}[Basic Formal Ontology (BFO)^].

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^].

Related documents include:

* The {s2_base_model_support}[S2 Base Types Information Model^];
* The {s2_base_data_types}[S2 Data Types Information Model^];

== Status

This specification is in the Stable state. The development version of this document can be found at {openehr_rm_latest_entity}[{openehr_rm_latest_entity}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {s2_rm_forum}[openEHR RM specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

