=== Entity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Entity (abstract)__*

h|*Description*
2+a|Continuant Entity whose identity is stable over its period of existence. Includes physical entities as well as other kinds of entities from the social, legal and business worlds, including intentional agents.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/base.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*domain_type*: `link:/releases/BASE/{base_release}/base.html#_terminology_term_class[Terminology_term^]`
a|URI to a detailed description of the concrete type of Entity represented by instances of any descendant of this class. For example, a specific archetype of `Person` might be used to represent Employees. This field might then contain a URI pointing to the relevant description of 'employee' within the owning organisation.

h|*0..1*
|*other_details*: `List<link:/releases/BASE/{base_release}/base.html#_node_class[Node^]>`
a|Archetypable generic description for this entity.

h|*0..1*
|*relationships*: `List<<<_entity_relationship_group_class,Entity_relationship_group>>>`
a|
|===
