=== Contact Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Contact*

h|*Description*
2+a|Description of a means of contact of a Party. Actual structure is archetyped.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/base_types.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*addresses*: `List<<<_address_class,Address>>>`
a|A set of address alternatives for this contact purpose and time validity combination.

h|*0..1*
|*time_validity*: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_date_class[Date^]>`
a|Valid time interval for this contact descriptor.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*purpose* (): `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Purpose for which this contact is used, e.g. mail,  daytime phone, etc. Taken from value of inherited `_name_` attribute.

h|*Invariants*
2+a|__Purpose_valid__: `purpose = name`
|===
