=== Material_entity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Material_entity<K>*

h|*Description*
2+a|A Material entity instance, e.g. a single prosthesis, blood sample, surgical glove etc.

h|*Inherit*
2+|`<<_physical_entity_class,Physical_entity>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*identifier*: `link:/releases/BASE/{base_release}/base.html#_rwe_id_ref_class[Rwe_id_ref^]`
a|Identifier assigned by owning / using institution or organization.

h|*0..1*
|*individual_attributes*: `List<link:/releases/BASE/{base_release}/base.html#_node_class[Node^]>`
a|Attributes of this material entity, as distinct from its type (such as a device type description). Typically includes serial number, UDI, etc.

h|*0..1*
|*lot_information*: `List<link:/releases/BASE/{base_release}/base.html#_node_class[Node^]>`
a|Information relating to a manufacturing or purchase lot, for volume procured items.

h|*0..1*
|*use_details*: `List<link:/releases/BASE/{base_release}/base.html#_node_class[Node^]>`
a|Details relating to use, location, maintenance.

h|*0..1*
|*other_identifiers*: `List<<<_id_use_class,Id_use>>>`
a|Other identifiers as required.
|===
